### ISSUE TITLE
can’t hold on the picker point and move it, only moving by press on android 

### ISSUE THREAD

**Issue by FatmaMahmoud698** [Naeemur/react-native-wheel-color-picker#13] opened 2021-07-04 09:34 UTC

**Comment by Naeemur** [comment] 2023-12-31 17:11
Since no other instance of this issue reported, I am closing this. If issue persists, try using prop useNativeLayout added in v1.3.0 (See README.md please.) If issue still persists, please reopen this issue with steps to reproduce.

**Closed as completed by Naeemur** 2023-12-31 17:11 UTC
