### ISSUE TITLE
Not working properly in scrollview

### ISSUE THREAD

**Issue by ashvanikumar623** [Naeemur/react-native-wheel-color-picker#26] opened 2022-03-03 16:25 UTC
When i use this color picker inside scrollview the color picker is not working smoothly

**Comment by GenGraphic** [comment] 2023-06-09 18:35
Same Problem here

**Comment by Naeemur** [comment] 2023-12-31 17:15
Since no other instance of this issue reported, I am closing this. If issue persists, try using prop useNativeLayout added in v1.3.0 (See README.md please.) If issue still persists, please reopen this issue with steps to reproduce.

**Closed as completed by Naeemur** 2023-12-31 17:15 UTC
